version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: erp-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: erp-redis
    restart: always
    ports:
      - "6379:6379"
  app:
    build: .
    container_name: erp-app
    restart: always
    command: npm run dev
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"

  cron:
    build: .
    container_name: erp-cron
    restart: always
    command: npm run cron
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  worker:
    build: .
    container_name: erp-worker
    restart: always
    command: npm run worker
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
